baseURL: https://godular.grwd.uk/
languageCode: "en-GB"
title: Godular
theme: godule

params:
  description: Hugo Modular CSS

# Set mount for theme assets directory
module:
  mounts:
  - source: /themes/godule/assets
    target: assets
